site:
  title: "Мой сайт"
  description: "Это мой первый YAML файл для сайта."
  author: "Ваше имя"
  url: "https://www.example.com"
pages:
  - title: "Главная"
    url: "/"
  - title: "О нас"
    url: "/about"
  - title: "Контакты"
    url: "/contact"
added comment by nasiba